image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - tht13.html-preview-vscode@0.2.5:ZLi/N2Y+HF6yM7IPnUHBEw==

tasks:
  - init: python3 file_builder.py
  
ports:
  - port: 3000
    onOpen: open-preview
